"""Base class of summons generated by character skills: abstract class
A character in the game should be an instant of the specific character class defined in each file"""
import itertools
from abc import ABC, abstractmethod
from queue import PriorityQueue
from typing import OrderedDict
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from gisim.classes.enums import PlayerID
from gisim.classes.message import Message

from .entity import Entity


class Summon(Entity, ABC):

    name: str
    usages: int
    player_id: PlayerID
    position: int = -1
    """Range from 0~3, should be set when adding a new summon to the summon zone. Initialized by -1"""
    active: bool = True
    _uuid: UUID = Field(default_factory=uuid4)

    def encode(self):
        return self.dict(exclude={"_uuid", "_logger"})

    @abstractmethod
    def msg_handler(self, msg_queue: PriorityQueue["Message"]) -> bool:
        ...
