'''Base class of summons generated by character skills: abstract class
A character in the game should be an instant of the specific character class defined in each file'''
from ...entity import Entity
from abc import ABCMeta, abstractmethod


class Summon(Entity, ABCMeta):
    def __init__(self):
        # TODO
        pass